#FastDfs的配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.0.202:22122
  web-server-url: http://192.168.0.202:9999/
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: 50
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 1000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10

logging:
  level:
    info: info
    error: error
    debug: debug
  file:
    path: ./logs
