server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 800
      min-spare: 30

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
